### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by XufengGAO** [Cascol-Chen/COLA#1]
Dear authors,
Thanks for your amazing work. May I ask when you plan to release the code?

best,
Xufeng

**Comment by Cascol-Chen** [comment]
Hi, thank you for your interest in your work. 

I'm sorry for the delay of code release as I am currently preparing for my PhD application. The expected release time would be around Jan. 2025. 

If you urgently need to run our code, please feel free to send an email to [chenguohao987@gmail.com](chenguohao987@gmail.com). I would provide you the preview code of our CoLA, where you should be able to reproduce our results via bash files, though the readability and the simplicity of our code need further improvement.
